version: "3.5"

x-shared-config:
  base: &base
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    user: "1069:1420"

  backend: &backend
    <<: *base
    environment:
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./backend:/app:cached
      - .sanity:/home/app/.config/sanity
      - backend_node_modules:/app/node_modules
    working_dir: /app

  frontend: &frontend
    <<: *base
    environment:
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    working_dir: /app

services:
  backend:
    <<: *backend
    build:
      context: .
    command: start
    depends_on:
      - proxy
    entrypoint: yarn
    env_file:
      - .env
      - .env.local
    ports:
      - 3333:3333
    working_dir: /app

  frontend:
    <<: *frontend
    build:
      context: .
    command: start
    depends_on:
      - proxy
    entrypoint: yarn
    env_file:
      - .env
      - .env.local
    ports:
      - 8000:8000
    working_dir: /app

  proxy:
    image: caddy:2.3.0-alpine
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  backend_node_modules:
  frontend_node_modules:
